---

- name: Install Discord
  hosts: ubuntu
  become: yes
  become_user: root
  vars:
    ansible_ssh_private_key_file: "~/.ssh/ansible"
  tasks:
    - name: Install discord
      snap:
        name: discord
        state: present