services:
  nginx:
    image: nginx:latest
    container_name: ReverseProxy
    restart: unless-stopped
    ports:
      - 80:80
      - 8000:8000
      - 8080:8080
    volumes:
      - /home/stiggu/reverse_proxy/conf/nginx.conf:/etc/nginx/nginx.conf

  firstapp:
    image: python:3.9
    container_name: fapp
    ports:
      - 9000:9000
    volumes:
      - /home/stiggu/reverse_proxy/firstapp:/code/
    command: >
        bash -c "cd code && pip install --no-cache-dir --upgrade -r /code/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 9000"

  secondapp:
    image: python:3.9
    container_name: sapp
    ports:
      - 9090:9090
    volumes:
      - /home/stiggu/reverse_proxy/secondapp:/code/
    command: > 
        bash -c "cd code && pip install --no-cache-dir --upgrade -r /code/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 9090"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email abelmunda@hotmail.com -d stiggu.dev --agree-tos